### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by yuchi** [rubenfonseca/titanium-keychain#1]
Great module with awesome API coverage, later next week I’ll have a look into replacing the module we’re currently using with yours.

Do you have any plan in creating tests (automated?) for the module? It’s such a critical feature that making tests for it would bring a lot of value in it.

@lele85, do you have any information to share about unit tests for native modules?

**Comment by rubenfonseca** [comment]
I never wrote tests for native modules, but I would love to read more about that for sure!

**Comment by yuchi** [comment]
I think that a simple example app with a spec written in `ti-mocha` could do the job.
After all you don’t need native tests, but tests on the Titanium side.

What do you think?

**Comment by rubenfonseca** [comment]
Oh I see and I agree. Do you know of a public example of writing tests using that style I can see?

**Comment by yuchi** [comment]
For `ti-mocha` see the [website](http://tonylukasavage.com/ti-mocha/) and [repo](https://github.com/tonylukasavage/ti-mocha).

Most of them look like this:

``` js
describe('A section', function () {
  it('a feature', function () {
    if (all_is_ok) {
      // do nothing
    }
    else {
      throw new Error("Oh gosh!");
    }
  });

  it('an async feature', function (done) {
    var timeoutId = setTimeout(function () {
      done(new Error("Why did it fired?"));
    });
    clearTimeout(timeoutId);
  });
});
```

**Comment by lele85** [comment]
@yuchi i agree with the "you just need test on the titanium side". I think that keychain native APIs are well tested by apple. You just need to ensure at funcional level that the mapping works as expected from the titanium side. ;-)

**Comment by yuchi** [comment]
Closing for obsolescence
