### ISSUE TITLE
Failure When Attempting to Build for Ti SDK 3.5.0.GA

### ISSUE THREAD

**Issue by adammagana** [rubenfonseca/titanium-keychain#2]
I wish to re-compile the module to be 64-bit compatible. When adjusting the necessary settings and preferences, as described in the [Ti SDK 3.5.0.GA release notes](http://docs.appcelerator.com/titanium/release-notes/?version=3.5.0.GA#modules), I get the following error upon running the `python build.py` command:

```
The following build commands failed:
    CompileC build/keychain.build/Release-iphoneos/keychain.build/Objects-normal/armv7/Com0x82KeychainModule.o Classes/Com0x82KeychainModule.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild failed
```

It is also important to note that I updated the `titanium.xcconfig` file to accommodate the updated SDK version. I cross referenced other, updated Ti modules to make sure that these changes were correct:

```
//
//
// CHANGE THESE VALUES TO REFLECT THE VERSION (AND LOCATION IF DIFFERENT)
// OF YOUR TITANIUM SDK YOU'RE BUILDING FOR
//
//
TITANIUM_SDK_VERSION = 3.5.0.GA


//
// THESE SHOULD BE OK GENERALLY AS-IS
//
TITANIUM_SDK = ~/Library/Application Support/Titanium/mobilesdk/osx/$(TITANIUM_SDK_VERSION)
TITANIUM_BASE_SDK = "$(TITANIUM_SDK)/iphone/include"
TITANIUM_BASE_SDK2 = "$(TITANIUM_SDK)/iphone/include/TiCore"
TITANIUM_BASE_SDK3 = "$(TITANIUM_SDK)/iphone/include/JavaScriptCore"
HEADER_SEARCH_PATHS= $(TITANIUM_BASE_SDK) $(TITANIUM_BASE_SDK2) $(TITANIUM_BASE_SDK3)
```

![screen shot 2015-01-28 at 12 30 59 pm](https://cloud.githubusercontent.com/assets/641064/5943046/8f48636c-a6e9-11e4-8ec8-e87aa2910a9f.png)
I have a few years experience with Titanium but very limited experience editing/building modules. Please bear with me if I left out anything important here and let me know if I can provide any more details. Thanks!

**Comment by bgnlordhelmut** [comment]
I'm running into the same issue, specifically "fatal error: 'TiModule.h' file not found". Seems like something's up internally to the module. If I manage to figure it out I'll post the solution here.

**Comment by adammagana** [comment]
@bgnlordhelmut I was actually able to figure it out and get the module to build. I intend to submit pull request with the adjustments.

**Comment by bgnlordhelmut** [comment]
Adam,

Could you give me a quick rundown of what you did if possible? Thanks much!

**Comment by adammagana** [comment]
@bgnlordhelmut I have a build that I am testing with currently (using the 2.1 version number that I can send to you). Do you have an email address you can share with me?

**Comment by bgnlordhelmut** [comment]
Yep that would be very helpful Adam. Hit me up at ryanhurley at gmail dot com.

**Comment by mmayantz2** [comment]
Umm can you guys help me out because I am having the same issue. Xcode complained that TiViewProxy.h and TiModule.h were missing, so I imported about 500 titanium classes into the folder, finally it complained about not having JavaScriptCore/TiCore.h.  I have tried just about everything to build this module in xcode but it continuously complains of missing core titanium classes.

any help? I can confirm as well that my xconfig file has all the correct paths set as I have vetted it a few times. much confused!

**Comment by adammagana** [comment]
@mmayantz2 Sorry for the delay I completely missed your comment. If you would like I can send you a working 64 bit build of the module. Let me know where I can send it and I'll have it over you asap.

**Comment by mmayantz2** [comment]
Hey thanks for getting back to me but I was actually having an issue
building another titanium module in 64 bit and I believe I posted on your
thread somewhat in error, that is to say I was experiencing a similar
issue, but I have since rectified it.

Max

**Comment by adammagana** [comment]
Awesome. Congrats on getting it to work. Best of luck!

**Comment by mmayantz2** [comment]
thanks, just out of curiosity however would you happen to know a more
complete resource than the appcelerator forums?

I am unable to build this brightcove module in xcode due to missing
titanium header file dependencies, despite the fact that all
titanium.xconfig settings are correct, what other forums do you know of? I
have found titanium help online to be quite sparse...

Regards

Max

**Comment by adammagana** [comment]
Try the folks over at [TiForward](http://tiforward.org/). It's new but they've been having some great discussions regarding future and current titanium development.

**Comment by ksouthworth** [comment]
@adammagana do you still have the 64-bit build of this module?  If so, could you please send it to me as well?  ksouthworth at gmail dot com
